#' Expand bbox
#' Sourced from https://rdrr.io/github/Chrisjb/basemapR/src/R/expand_bbox.R
#' A function to take a bounding box (generated using st_bbox) and expand it by x meters in the X direction and y meters in the Y direction.
#'
#' @description A function to take a bounding box (generated using st_bbox) and expand it by x meters in the X direction and y meters in the Y direction.
#' @import sf
#' @param bbox a bounding box generated by sf::st_bbox() or named numeric vector with xmin, ymin, xmax, ymax.
#' @param X the distance in meters that we want to expand the bounding box by in the X direction
#' @param Y the distance in meters that we want to expand the bounding box by in the Y direction
#' @param X2 if specified, the meters in the Easterly direction and meters X becomes meters in the Westerly direction.
#' @param Y2 if specified, the meters to the South. meters Y becomes metres to the North.
#' @param crs_out what epsg coordinate system to return the bbox in. Defaults to lat/lng (4326).
#'
#' @return a named numeric vector of bbox extents. This can be converted into an sf object using sf::st_as_sfc(). Coordinates are in lat/lng (4326).
#'
#' @export

f.expand.bbox <- function(bbox, X, Y, X2 = X, Y2 = Y,
                        crs_out = 4326) {
  bbox <- bbox |>
    sf::st_as_sfc() |>
    sf::st_transform(crs = 4326) |>
    sf::st_bbox()


  bbox["xmin"] <- bbox["xmin"] - (X / 6370000) * (180 / pi) / cos(bbox["xmin"] * pi / 180)
  bbox["xmax"] <- bbox["xmax"] + (X2 / 6370000) * (180 / pi) / cos(bbox["xmax"] * pi / 180)
  bbox["ymin"] <- bbox["ymin"] - (Y / 6370000) * (180 / pi)
  bbox["ymax"] <- bbox["ymax"] + (Y2 / 6370000) * (180 / pi)

  bbox |>
    sf::st_as_sfc() |>
    sf::st_transform(crs = crs_out) |>
    sf::st_bbox()
}
