#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @import rlang
#' @importFrom AzureAuth get_azure_token
#' @importFrom AzureAuth list_azure_tokens
#' @importFrom AzureAuth load_azure_token
#' @importFrom AzureStor create_storage_dir
#' @importFrom AzureStor delete_storage_file
#' @importFrom AzureStor list_storage_files
#' @importFrom AzureStor storage_container
#' @importFrom AzureStor storage_dir_exists
#' @importFrom AzureStor storage_download
#' @importFrom AzureStor storage_endpoint
#' @importFrom AzureStor storage_file_exists
#' @importFrom AzureStor storage_load_rdata
#' @importFrom AzureStor storage_load_rds
#' @importFrom AzureStor storage_read_csv
#' @importFrom AzureStor storage_save_rds
#' @importFrom AzureStor storage_upload
#' @importFrom AzureStor storage_write_csv
#' @importFrom blastula compose_email
#' @importFrom blastula md
#' @importFrom cli cli_abort
#' @importFrom cli cli_alert
#' @importFrom cli cli_alert_danger
#' @importFrom cli cli_alert_info
#' @importFrom cli cli_alert_success
#' @importFrom cli cli_alert_warning
#' @importFrom cli cli_h1
#' @importFrom cli cli_process_done
#' @importFrom cli cli_process_start
#' @importFrom cli cli_progress_done
#' @importFrom cli cli_progress_step
#' @importFrom dplyr across
#' @importFrom dplyr all_of
#' @importFrom dplyr anti_join
#' @importFrom dplyr any_of
#' @importFrom dplyr arrange
#' @importFrom dplyr as_tibble
#' @importFrom dplyr between
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_match
#' @importFrom dplyr case_when
#' @importFrom dplyr coalesce
#' @importFrom dplyr contains
#' @importFrom dplyr count
#' @importFrom dplyr desc
#' @importFrom dplyr distinct
#' @importFrom dplyr ends_with
#' @importFrom dplyr enquo
#' @importFrom dplyr everything
#' @importFrom dplyr filter
#' @importFrom dplyr full_join
#' @importFrom dplyr group_by
#' @importFrom dplyr if_else
#' @importFrom dplyr inner_join
#' @importFrom dplyr join_by
#' @importFrom dplyr lag
#' @importFrom dplyr last
#' @importFrom dplyr left_join
#' @importFrom dplyr matches
#' @importFrom dplyr mutate
#' @importFrom dplyr mutate_at
#' @importFrom dplyr n
#' @importFrom dplyr pull
#' @importFrom dplyr reframe
#' @importFrom dplyr rename
#' @importFrom dplyr rename_with
#' @importFrom dplyr rowwise
#' @importFrom dplyr select
#' @importFrom dplyr slice
#' @importFrom dplyr starts_with
#' @importFrom dplyr summarise
#' @importFrom dplyr summarize
#' @importFrom dplyr syms
#' @importFrom dplyr tibble
#' @importFrom dplyr ungroup
#' @importFrom dplyr where
#' @importFrom flextable add_footer_lines
#' @importFrom flextable add_footer_row
#' @importFrom flextable add_header_lines
#' @importFrom flextable add_header_row
#' @importFrom flextable align
#' @importFrom flextable as_grouped_data
#' @importFrom flextable autofit
#' @importFrom flextable bg
#' @importFrom flextable bold
#' @importFrom flextable colformat_double
#' @importFrom flextable color
#' @importFrom flextable flextable
#' @importFrom flextable fontsize
#' @importFrom flextable fp_border_default
#' @importFrom flextable hline
#' @importFrom flextable save_as_image
#' @importFrom flextable set_header_df
#' @importFrom flextable set_header_labels
#' @importFrom flextable theme_booktabs
#' @importFrom flextable vline
#' @importFrom flextable width
#' @importFrom forcats fct_inorder
#' @importFrom forcats fct_na_value_to_level
#' @importFrom forcats fct_rev
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 alpha
#' @importFrom ggplot2 coord_flip
#' @importFrom ggplot2 coord_sf
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_line
#' @importFrom ggplot2 element_rect
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 facet_grid
#' @importFrom ggplot2 facet_wrap
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 geom_col
#' @importFrom ggplot2 geom_hline
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_rect
#' @importFrom ggplot2 geom_sf
#' @importFrom ggplot2 geom_sf_text
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 geom_tile
#' @importFrom ggplot2 geom_vline
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggsave
#' @importFrom ggplot2 ggtitle
#' @importFrom ggplot2 guide_legend
#' @importFrom ggplot2 guides
#' @importFrom ggplot2 label_wrap_gen
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 position_jitter
#' @importFrom ggplot2 position_stack
#' @importFrom ggplot2 scale_color_manual
#' @importFrom ggplot2 scale_fill_brewer
#' @importFrom ggplot2 scale_fill_distiller
#' @importFrom ggplot2 scale_fill_manual
#' @importFrom ggplot2 scale_shape_manual
#' @importFrom ggplot2 scale_size_identity
#' @importFrom ggplot2 scale_x_date
#' @importFrom ggplot2 scale_x_discrete
#' @importFrom ggplot2 scale_y_continuous
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_bw
#' @importFrom ggplot2 theme_classic
#' @importFrom ggplot2 unit
#' @importFrom ggplot2 xlab
#' @importFrom ggplot2 ylab
#' @importFrom ggpubr annotate_figure
#' @importFrom ggpubr get_legend
#' @importFrom ggpubr ggarrange
#' @importFrom ggpubr text_grob
#' @importFrom ggpubr theme_pubr
#' @importFrom ggrepel geom_label_repel
#' @importFrom ggspatial annotation_scale
#' @importFrom git2r add
#' @importFrom git2r commit
#' @importFrom git2r discover_repository
#' @importFrom git2r push
#' @importFrom git2r repository
#' @importFrom glue glue
#' @importFrom httr content
#' @importFrom httr GET
#' @importFrom janitor row_to_names
#' @importFrom lifecycle badge
#' @importFrom lifecycle deprecate_warn
#' @importFrom lifecycle deprecated
#' @importFrom lifecycle is_present
#' @importFrom lubridate as_date
#' @importFrom lubridate epiweek
#' @importFrom lubridate floor_date
#' @importFrom lubridate month
#' @importFrom lubridate today
#' @importFrom lubridate weeks
#' @importFrom lubridate year
#' @importFrom lubridate years
#' @importFrom magick image_animate
#' @importFrom magick image_join
#' @importFrom magick image_read
#' @importFrom magick image_write
#' @importFrom Microsoft365R get_business_outlook
#' @importFrom Microsoft365R get_sharepoint_site
#' @importFrom Microsoft365R get_team
#' @importFrom officer add_slide
#' @importFrom officer block_list
#' @importFrom officer external_img
#' @importFrom officer fp_text
#' @importFrom officer fpar
#' @importFrom officer ftext
#' @importFrom officer layout_properties
#' @importFrom officer layout_summary
#' @importFrom officer ph_location
#' @importFrom officer ph_location_label
#' @importFrom officer ph_location_type
#' @importFrom officer ph_with
#' @importFrom officer read_pptx
#' @importFrom officer unordered_list
#' @importFrom prettyunits pretty_bytes
#' @importFrom prettyunits pretty_sec
#' @importFrom purrr map
#' @importFrom purrr map_chr
#' @importFrom readr read_csv
#' @importFrom readr read_rds
#' @importFrom readr write_csv
#' @importFrom readr write_lines
#' @importFrom readr write_rds
#' @importFrom readxl read_excel
#' @importFrom rvg dml
#' @importFrom scales brewer_pal
#' @importFrom scales comma
#' @importFrom scales label_percent
#' @importFrom scales number_format
#' @importFrom scales percent
#' @importFrom sf sf_use_s2
#' @importFrom sf st_as_sf
#' @importFrom sf st_as_sfc
#' @importFrom sf st_bbox
#' @importFrom sf st_centroid
#' @importFrom sf st_coordinates
#' @importFrom sf st_crop
#' @importFrom sf st_crs
#' @importFrom sf st_intersection
#' @importFrom sf st_is_empty
#' @importFrom sf st_make_valid
#' @importFrom sf st_sample
#' @importFrom sf st_touches
#' @importFrom sf st_transform
#' @importFrom stringr regex
#' @importFrom stringr str_c
#' @importFrom stringr str_count
#' @importFrom stringr str_detect
#' @importFrom stringr str_ends
#' @importFrom stringr str_extract
#' @importFrom stringr str_replace
#' @importFrom stringr str_replace_all
#' @importFrom stringr str_split
#' @importFrom stringr str_squish
#' @importFrom stringr str_starts
#' @importFrom stringr str_to_lower
#' @importFrom stringr str_to_title
#' @importFrom stringr str_to_upper
#' @importFrom stringr str_trim
#' @importFrom tibble rownames_to_column
#' @importFrom tibble tibble
#' @importFrom tidyr complete
#' @importFrom tidyr drop_na
#' @importFrom tidyr expand_grid
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr pivot_wider
#' @importFrom tidyr replace_na
#' @importFrom tidyr separate
#' @importFrom tidyr separate_wider_regex
#' @importFrom tidyr unite
#' @importFrom tidyr unnest
#' @importFrom utils download.file
#' @importFrom utils globalVariables
#' @importFrom utils head
#' @importFrom vctrs vec_duplicate_detect
#' @importFrom writexl write_xlsx
#' @importFrom zoo as.yearmon
## usethis namespace: end
NULL
